### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by adah1972** [ponychicken/WebsterParser#1]
Thanks for the terrific work! I think it is very useful, but I do find some issues.

One thing is question mark. I see many question marks, many in the place of pronunciations. E.g. I can see "**Ap′ple** (ăp"p'l), _n_.", but only "**Word** (?), _n_.".

I also see some U+FFFD symbols. E.g. in "Venal", I can see "[L. _venalis_, from _venus_ sale; akin to Gr. � price, Skr. _vasna_: cf. F. _vénal_.]".

I would also suggest using an alternative font.  Other dictionaries seem to be using Garamond, which looks nicer than Times (which I suppose you are using).

Thank you for checking the feedback.

**Comment by ponychicken** [comment]
Hey, thanks for the feedback.
1. The missing pronunciations are actually also missing in the source files (Project Guttenberg) I use. I'm not sure why they weren't transcribed, but there no easy way for me to add them.
2. The same applies here. &?; is used in the transcription, which I convert to xFFFD.
3. I thought I embedded the open source Gentium font, since it has a pretty good unicode code support. Maybe it's not loaded on your device? Could you send a screenshot?

**Comment by ponychicken** [comment]
I checked in the paper version and it seems that the Guttenberg transcriptions is laking in a lot of places. Unfortunately it is the only free version I know of.

**Comment by adah1972** [comment]
Hi DieBuche,

Thanks for the answer.

For 1/2, I noticed that www.dict.org has the information in a transcribed form. Maybe you can have a look. It mentions that the source files are available at http://ftp.gnu.org/gnu/gcide/.

For 3, I installed the Gentium font, and it does show a difference (thanks!). Please compare the two screen shots (I am using OS X Lion). Yup, I like the look with Gentium :-).
![original](https://cloud.githubusercontent.com/assets/2137834/4101472/cd53264c-30ec-11e4-8d7d-62c40fd8074a.png)
![gentium](https://cloud.githubusercontent.com/assets/2137834/4101471/cd4d4d30-30ec-11e4-825c-a2ccaacf9db3.png)

**Comment by ponychicken** [comment]
I uploaded a new release which is now based on GCIDE. Thanks for the hint!

![screenshot 2014-09-02 14 48 40](https://cloud.githubusercontent.com/assets/183302/4118329/ad1da578-329f-11e4-88c3-0256caf85571.png)

**Comment by adah1972** [comment]
I am definitely loving it. Much nicer.

Two minor issues that might be worth fixing:
- I saw "‖" before the head word "Cosmos". It is not present in the source file, as far as I can see.
- When poetry is quoted, the space between lines is now a blank line and is larger than the space between the quotations. I am not sure whether it is a regression, as the image on "vagabond" above looked good (bad on my side now), but my image on "flash" showed the same problem.

**Comment by ponychicken** [comment]
1. Cosmos has this double bar is my source (also in CIDE). 

> This precedes words marked with a double vertical bar in
> the original dictionary, signifying that the word was
> adopted directly into English without modification of
> the spelling.

Which makes sense for cosmos, since it's straight up greek.
1. The Vagabond screenshot was done with the new version. Are you seeing something else? If yes, screenshot please and also OS X version.

**Comment by adah1972** [comment]
Thanks for the explanation on "cosmos".

The screen shot is attached. The system is OS X Lion.

![screen](https://cloud.githubusercontent.com/assets/2137834/4166549/3629e110-350c-11e4-95e3-29502a59b43b.png)

I also tried on an old Snow Leopard machine, and the result was good. Surprising! On both machines the Gentium font is now not needed.

**Comment by jeffbyrnes** [comment]
Based on the last comment, seems like this can be closed.

**Comment by adah1972** [comment]
Yes. Actually it seems only Lion had this problem. It works fine also on Sierra and High Sierra.
