### ISSUE TITLE
Activate Phonetic Transcription for the American pronunciation in this dictionary

### ISSUE THREAD

**Issue by shahrokh-bahtooei** [ponychicken/WebsterParser#109]
Using Merriam-Webster's dictionary is really helpful to determine the American pronunciation for a given word in Diacritical alphabets, not IPA. How can we activate the phonetic transcription in this dictionary using Dictionary.app on macOS?

**Comment by jeffbyrnes** [comment]
The pronunciation is included with the dictionary, it’s part & parcel, so I think it’s beyond this project’s ability to satisfy what you’re looking for.

Maybe open an issue with the upstream project, [GNU CIDE](https://gcide.gnu.org.ua)? There’s a link to contact the maintainers.
