### ISSUE TITLE
Issue with special characters being replaced with question marks within definitions

### ISSUE THREAD

**Issue by appledispatch** [ponychicken/WebsterParser#110]
After installing the 1913 Webster's folder in the macOS Sonoma Dictionaries directory, I'm seeing asterisks and other special characters replaced with question marks within word entries. Is there a way to fix this?

**Comment by jeffbyrnes** [comment]
These are, unfortunately, present in the source material in most, if not all, cases. You’ll need to look upstream & see if you can submit a ticket or even a patch to the [GNU GCIDE project](https://gcide.gnu.org.ua/).

You can read about a similar (or same?) issue in #26, specifically please [see my comment](https://github.com/websterParser/WebsterParser/issues/26#issuecomment-1010024123).

**Comment by appledispatch** [comment]
Thanks for your quick and helpful reply. The issue you cited in a similar thread is indeed the same problem I'm referring to (question marks in diamonds). I understand now that this is a source code problem as you mentioned.

The way I initially confirmed my suspicions about the missing characters was through an interesting online dictionary project that must be using a different source without these encoding issues present: https://www.websters1913.com/

I will continue to use your version in the macOS Dictionary as it is so incredibly useful and convenient. Thank you for your work on the project and I exhort you to keep it going. Maybe someday these special characters will be fixed in the source project code.

**Comment by jeffbyrnes** [comment]
@appledispatch you’re welcome! And credit to the original developer @ponychicken, I’ve simply glommed on & contributed where I could.

Interesting to learn about websters1913.com! There’s nothing there that shows the source of their data, so who knows?
