### ISSUE TITLE
make commands fail with "Cannot get the real path for source"

### ISSUE THREAD

**Issue by sheonhan** [ponychicken/WebsterParser#23]
Hi @ponychicken, thanks for creating this project! I've been trying to run this on my machine but ran into an issue. 
I ran the script in README, but it looks like `make` commands fail. 

Maybe I'm missing a step here? The message that says "`Finished reading files: []`" seemed a little suspicious to me, and I was wondering if I need to put the actual zip file somewhere.

The following is what I see:
```sh
> websterParser@1.3.2 start ~/WebsterParser
> ts-node index.ts

Finished reading files: []
"""/Applications/Utilities/Dictionary Development Kit"/bin"/build_dict.sh" -v 10.11  "websters-1913" dict.xml styles.css info.plist
- Building websters-1913.dictionary.
- Checking source.
Unable to open dict.xml
Error.
make: *** [all] Error 1
echo "Installing into ~/Library/Dictionaries".
Installing into ~/Library/Dictionaries.
mkdir -p ~/Library/Dictionaries
ditto --noextattr --norsrc ./objects/"websters-1913".dictionary  ~/Library/Dictionaries/"websters-1913".dictionary
ditto: Cannot get the real path for source './objects/websters-1913.dictionary'
make: *** [install] Error 1
```

FWIW, I'm on Big Sur (Version 11.1) and using Xcode 12.3.

**Comment by j-f1** [comment]
It looks like they switched to submodules but didn’t add `git submodule update --init` to the list of things to run. That should pull down the data files.

**Comment by sheonhan** [comment]
That was it. Thanks!

**Comment by jeffbyrnes** [comment]
Thanks y’all, I’ve updated the README to clarify that.
