### ISSUE TITLE
Greek letters not recognized

### ISSUE THREAD

**Issue by apkawel** [ponychicken/WebsterParser#26]
First, thank you for your work on this. I was using another version of Webster's 1913 on macOS, and your typesetting is much better!

Second, you may be aware of this already, but it appears that some Greek letters are not rendering correctly. Please see screenshot below. (Others do render correctly: for example, in the entry for "eat".)

Thanks for your consideration!
<img width="802" alt="Screen Shot 2021-05-11 at 2 48 57 PM" src="https://user-images.githubusercontent.com/32605043/117869208-83a67800-b268-11eb-800e-bc757f75d662.png">

**Comment by jeffbyrnes** [comment]
@apkawel thanks for filing an issue for this. I noticed it some time ago, but wasn’t able to work out how to fix it. These characters use an unusual syntax for denoting the characters.

**Comment by est** [comment]
are you refering to the three question marks in the screenshot?

https://gutenberg.org/cache/epub/668/pg668.txt

looking up the source it looks like it was stored as ??? in Project Gutenberg.

**Comment by jeffbyrnes** [comment]
Yep, that’s what I’m referring to. That “question mark in a diamond” is what replaces unknown characters when there are encoding issues.

**Comment by jeffbyrnes** [comment]
Looks like Project Gutenberg _also_ didn’t decode it correctly either, the `&?;` looks like an HTML entity (though those are usually denoted via a `&` followed by an integer, ending with `;`).

**Comment by est** [comment]
So what can we look beyond Project Gutenberg? The actual dictionary book in paper? 

Can we make an educated guess what the was the three "question mark in diamond" was about?

**Comment by jeffbyrnes** [comment]
@est thankfully, our data source (GCIDE) is, I think, one thing that Gutenberg uses to generate its text, so I _think_ there’s a way to fix this.

There’s some PRs open right now to solve other issues, so lemme focus on those right now & then come back to this & see if we can sort this out.

**Comment by jeffbyrnes** [comment]
Looking at the GCIDE source, here’s what the entry for “Smoke” looks like:

```
<p><ent>Smoke</ent><br/
<hw>Smoke</hw> <pr>(sm<omac/k)</pr>, <pos>n.</pos> <ety>[AS. <ets>smoca</ets>, fr. <ets>sme<oacute/can</ets> to smoke; akin to LG. & D. <ets>smook</ets> smoke, Dan. <ets>sm<oum/g</ets>, G. <ets>schmauch</ets>, and perh. to Gr. <?/<?/<?/ to burn in a smoldering fire; cf. Lith. <ets>smaugti</ets> to choke.]</ety> <sn>1.</sn> <def>The visible exhalation, vapor, or substance that escapes, or expelled, from a burning body, especially from burning vegetable matter, as wood, coal, peat, or the like.</def><br/
[<source>1913 Webster</source>]</p>
```

You can see the `Gr. <?/<?/<?/` meaning this is in our source material. So unfortunately, it’s something that’ll need to be taken up with the upstream project. Their website is here: https://savannah.gnu.org/projects/gcide/
