### ISSUE TITLE
MacOS Dictionary App Hangs Up While searching certain words

### ISSUE THREAD

**Issue by suhailasif** [ponychicken/WebsterParser#56]
- I have installed the webster's-1913.dictionary folder in MacOS's dictionary folder
- The dictionary app Hangs up while searching certain words such as contrite, Love etc. 
- The app works fine for a better part of dictionary searches. 
- These words searched in other dictionaries installed in dictionary app return queries without hanging up. 

**Using MacOS Monterey, Intel Chip**

**Comment by jeffbyrnes** [comment]
Can confirm it hangs for me, too, when searching “contrite” on my Mac. (latest Monterey, Intel chipset as well).

**Comment by cratermoon** [comment]
Same here. The words "synoptic", "student", and "store", for example, cause the dictionary to hang for a while, the cursor turns to the "spinning beachball of death", and it shows the entry for "stooge".

**Comment by jeffbyrnes** [comment]
I’ve poked at this a few times since first noticing it; it’s some sort of syntax error or conversion error, but unfortunately the format of the original source isn’t something I understand very well, so I don’t really know where to begin with debugging.

If anyone has any experience w/ GCIDE and the format they use, perhaps they can help?

Interestingly, these entries _can_ be seen in the online version of GCIDE. Here’s [“synoptic”](https://gcide.gnu.org.ua/?q=synoptic&define=Define&strategy=.) for example.

**Comment by cratermoon** [comment]
> I’ve poked at this a few times since first noticing it; it’s some sort of syntax error or conversion error, but unfortunately the format of the original source isn’t something I understand very well, so I don’t really know where to begin with debugging.
> 
> If anyone has any experience w/ GCIDE and the format they use, perhaps they can help?
> 
> Interestingly, these entries _can_ be seen in the online version of GCIDE. Here’s [“synoptic”](https://gcide.gnu.org.ua/?q=synoptic&define=Define&strategy=.) for example.

I went back to the 1.3.4 release zip and installed that. It seems to work OK. The diff between 1.3.4 and 1.3.6 suggests some changes in index.ts might be a good place to start. Sorry I can't be more helpful, though.

**Comment by jeffbyrnes** [comment]
Thanks @cratermoon, that’s great to know. Clearly a regression of some sort was introduced. I’ll try to make some time to dig in & look, but having you narrow it down like that is a huge help!

**Comment by dangduc** [comment]
> I went back to the 1.3.4 release zip and installed that. It seems to work OK. The diff between 1.3.4 and 1.3.6 suggests some changes in index.ts might be a good place to start. Sorry I can't be more helpful, though.

+1: Incrementally typing the letters to "structure" hangs the dictionary.app for me. Workaround was to switch to 1.3.4.

**Comment by jeffbyrnes** [comment]
Thanks for confirming that 1.3.5 & beyond are where this regression crept in. There were some pretty major refactors that happened in there so something must have come unstuck.

**Comment by jeffbyrnes** [comment]
I’m validating that #81 did the trick, and if so, I’ll cut a new release for y’all!

**Comment by jeffbyrnes** [comment]
Ok, new build with fixes from #81 fix this! I’ll publish a new `.dictionary` shortly.
